///////////////////////////////////////////////////////////
//  BankaKrvi.cs
//  Implementation of the Class BankaKrvi
//  Generated by Enterprise Architect
//  Created on:      25-jul-2018 20:36:05
//  Original author: mixa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;




namespace Baza.Baza
{
	/// <summary>
	/// Jedinica transfuzije
	/// </summary>
	public class BankaKrvi {

        private int id;
		private string adresa;
		private int brojBanke;
        private Pacijent pacijent;
        private JedinicaTransfuzije jedinicaTransfuzije;

        public string Adresa { get => adresa; set => adresa = value; }
        public int BrojBanke { get => brojBanke; set => brojBanke = value; }
        public Pacijent Pacijent { get => pacijent; set => pacijent = value; }
        public JedinicaTransfuzije JedinicaTransfuzije { get => jedinicaTransfuzije; set => jedinicaTransfuzije = value; }
        public int Id { get => id; set => id = value; }

        public BankaKrvi(){

		}

		~BankaKrvi(){

		}

	}//end BankaKrvi

}//end namespace CrveniKrst