///////////////////////////////////////////////////////////
//  BankaKrvi.cs
//  Implementation of the Class BankaKrvi
//  Generated by Enterprise Architect
//  Created on:      25-jul-2018 20:36:05
//  Original author: mixa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using CrveniKrst;
namespace CrveniKrst {
	/// <summary>
	/// Jedinica transfuzije
	/// </summary>
	public class BankaKrvi {

		private string adresa;
		private int brojBanke;
		public CrveniKrst.Pacijent m_Pacijent;
		public CrveniKrst.JedinicaTransfuzije m_JedinicaTransfuzije;

		public BankaKrvi(){

		}

		~BankaKrvi(){

		}

	}//end BankaKrvi

}//end namespace CrveniKrst