///////////////////////////////////////////////////////////
//  Donor.cs
//  Implementation of the Class Donor
//  Generated by Enterprise Architect
//  Created on:      25-jul-2018 20:36:05
//  Original author: mixa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace CrveniKrst {
	public class Donor {

		private int id;
		private string ime;
		private char[3] krvnaGrupa;
		private string prezime;

		public Donor(){

		}

		~Donor(){

		}

	}//end Donor

}//end namespace CrveniKrst