///////////////////////////////////////////////////////////
//  Donor.cs
//  Implementation of the Class Donor
//  Generated by Enterprise Architect
//  Created on:      25-jul-2018 20:36:05
//  Original author: mixa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Common.DTO;

namespace Baza.Baza
{
	public class Donor {

		private int id;
		private string ime;
		private char[] krvnaGrupa = new char[3];
		private string prezime;

		public Donor(){

		}

<<<<<<< HEAD
        public Donor(DonorDTO donorDTO)
        {
            this.Ime = donorDTO.Ime;
            this.KrvnaGrupa = donorDTO.KrvnaGrupa;
            this.Prezime = donorDTO.Prezime;
        }

=======
>>>>>>> 3391f6091eefa9c4d3d6dfa8d784624df25b3975
        public Donor(int id, string ime, char[] krvnaGrupa, string prezime)
        {
            this.Id = id;
            this.Ime = ime;
            this.KrvnaGrupa = krvnaGrupa;
            this.Prezime = prezime;
        }

        ~Donor(){

		}

        public int Id { get => id; set => id = value; }
        public string Ime { get => ime; set => ime = value; }
        public char[] KrvnaGrupa { get => krvnaGrupa; set => krvnaGrupa = value; }
        public string Prezime { get => prezime; set => prezime = value; }
<<<<<<< HEAD

        public bool MatchesFilter(DonorDTO donorDTO)
        {
            if(donorDTO.Id!=0 && donorDTO.Id != id)
            {
                return false;
            }
            if(!donorDTO.Ime.Trim().Equals("") && !donorDTO.Ime.Equals(ime))
            {
                return false;
            }
            if (!donorDTO.Prezime.Trim().Equals("") && !donorDTO.Prezime.Equals(prezime))
            {
                return false;
            }
            string krvnaGrupaDonora = new string(krvnaGrupa);
            string krvnaGrupaDonorDTO = new string(donorDTO.KrvnaGrupa);
            if(!krvnaGrupaDonorDTO.Trim().Equals("") && !krvnaGrupaDonorDTO.Equals(krvnaGrupaDonora))
            {
                return false;
            }





            return true;
        }
=======
>>>>>>> 3391f6091eefa9c4d3d6dfa8d784624df25b3975
    }//end Donor

}//end namespace CrveniKrst