///////////////////////////////////////////////////////////
//  Donor.cs
//  Implementation of the Class Donor
//  Generated by Enterprise Architect
//  Created on:      25-jul-2018 20:36:05
//  Original author: mixa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace CrveniKrst {
	public class Donor {

		private int id;
		private string ime;
		private char[] krvnaGrupa = new char[3];
		private string prezime;

		public Donor(){

		}

        public Donor(int id, string ime, char[] krvnaGrupa, string prezime)
        {
            this.Id = id;
            this.Ime = ime;
            this.KrvnaGrupa = krvnaGrupa;
            this.Prezime = prezime;
        }

        ~Donor(){

		}

        public int Id { get => id; set => id = value; }
        public string Ime { get => ime; set => ime = value; }
        public char[] KrvnaGrupa { get => krvnaGrupa; set => krvnaGrupa = value; }
        public string Prezime { get => prezime; set => prezime = value; }
    }//end Donor

}//end namespace CrveniKrst