///////////////////////////////////////////////////////////
//  JedinicaTransfuzije.cs
//  Implementation of the Class JedinicaTransfuzije
//  Generated by Enterprise Architect
//  Created on:      25-jul-2018 20:36:05
//  Original author: mixa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;




namespace Baza.Baza
{
	public class JedinicaTransfuzije {

        private int id;
		private int kolicina;
		private char[] krvnaGrupa = new char[3];
		private string oznaka;
<<<<<<< HEAD
		private Donor m_Donor;
=======
		private CrveniKrst.Donor m_Donor;
>>>>>>> 3391f6091eefa9c4d3d6dfa8d784624df25b3975

		public JedinicaTransfuzije(){

		}

		~JedinicaTransfuzije(){

		}

        public int Kolicina { get => kolicina; set => kolicina = value; }
        public char[] KrvnaGrupa { get => krvnaGrupa; set => krvnaGrupa = value; }
        public string Oznaka { get => oznaka; set => oznaka = value; }
        public Donor Donor { get => m_Donor; set => m_Donor = value; }
        public int Id { get => id; set => id = value; }
    }//end JedinicaTransfuzije

}//end namespace CrveniKrst