///////////////////////////////////////////////////////////
//  JedinicaTransfuzije.cs
//  Implementation of the Class JedinicaTransfuzije
//  Generated by Enterprise Architect
//  Created on:      25-jul-2018 20:36:05
//  Original author: mixa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using CrveniKrst;
namespace CrveniKrst {
	public class JedinicaTransfuzije {

		private int kolicina;
		private char[3] krvnaGrupa;
		private string oznaka;
		public CrveniKrst.Donor m_Donor;

		public JedinicaTransfuzije(){

		}

		~JedinicaTransfuzije(){

		}

	}//end JedinicaTransfuzije

}//end namespace CrveniKrst