///////////////////////////////////////////////////////////
//  Pacijent.cs
//  Implementation of the Class Pacijent
//  Generated by Enterprise Architect
//  Created on:      25-jul-2018 20:36:05
//  Original author: mixa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace CrveniKrst {
	/// <summary>
	/// Primalac transfuzije
	/// </summary>
	public class Pacijent {

		private int id;
		private string ime;
		private char[3] krvnaGrupa;
		private string prezime;

		public Pacijent(){

		}

		~Pacijent(){

		}

	}//end Pacijent

}//end namespace CrveniKrst